// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test
void test(int persons, int days);
RcppExport SEXP _Repideux_test(SEXP personsSEXP, SEXP daysSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type persons(personsSEXP);
    Rcpp::traits::input_parameter< int >::type days(daysSEXP);
    test(persons, days);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Repideux_test", (DL_FUNC) &_Repideux_test, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Repideux(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
