# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(persons = 100L, days = 10L) {
    invisible(.Call(`_Repideux_test`, persons, days))
}

